# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/design_constraints.xdc

# Block Designs: bd/design_5/design_5.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5 || ORIG_REF_NAME==design_5} -quiet] -quiet

# IP: bd/design_5/ip/design_5_processing_system7_0_0/design_5_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_processing_system7_0_0 || ORIG_REF_NAME==design_5_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_do_convolution_0_0/design_5_do_convolution_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_do_convolution_0_0 || ORIG_REF_NAME==design_5_do_convolution_0_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_axi_fifo_mm_s_0_0/design_5_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==design_5_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_axi_timer_0_0/design_5_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_axi_timer_0_0 || ORIG_REF_NAME==design_5_axi_timer_0_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_rst_ps7_0_100M_0/design_5_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_5_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_ps7_0_axi_periph_0/design_5_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_5_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_xbar_0/design_5_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_xbar_0 || ORIG_REF_NAME==design_5_xbar_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_auto_pc_0/design_5_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_auto_pc_0 || ORIG_REF_NAME==design_5_auto_pc_0} -quiet] -quiet

# XDC: bd/design_5/design_5_ooc.xdc
