// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "out_stream_V"
#define AUTOTB_TVOUT_out_stream_V  "../tv/cdatafile/c.do_convolution.autotvout_out_stream_V.dat"
#define AUTOTB_TVIN_out_stream_V  "../tv/cdatafile/c.do_convolution.autotvin_out_stream_V.dat"
#define WRAPC_STREAM_SIZE_OUT_out_stream_V  "../tv/stream_size/stream_size_out_out_stream_V.dat"
#define WRAPC_STREAM_EGRESS_STATUS_out_stream_V  "../tv/stream_size/stream_egress_status_out_stream_V.dat"
// wrapc file define: "in_stream_V"
#define AUTOTB_TVIN_in_stream_V  "../tv/cdatafile/c.do_convolution.autotvin_in_stream_V.dat"
#define WRAPC_STREAM_SIZE_IN_in_stream_V  "../tv/stream_size/stream_size_in_in_stream_V.dat"
#define WRAPC_STREAM_INGRESS_STATUS_in_stream_V  "../tv/stream_size/stream_ingress_status_in_stream_V.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "out_stream_V"
#define AUTOTB_TVOUT_PC_out_stream_V  "../tv/rtldatafile/rtl.do_convolution.autotvout_out_stream_V.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			out_stream_V_depth = 0;
			in_stream_V_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{out_stream_V " << out_stream_V_depth << "}\n";
			total_list << "{in_stream_V " << in_stream_V_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int out_stream_V_depth;
		int in_stream_V_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern void do_convolution (
hls::stream<int > (&out_stream),
hls::stream<int > (&in_stream));

void AESL_WRAP_do_convolution (
hls::stream<int > (&out_stream),
hls::stream<int > (&in_stream))
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;

		// define output stream variables: "out_stream"
		std::vector<int > aesl_tmp_0;
		int aesl_tmp_1;
		int aesl_tmp_2 = 0;

		// read output stream size: "out_stream"
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_stream_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_stream_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_stream_V, AESL_token); // pop_size
			aesl_tmp_1 = atoi(AESL_token.c_str());
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_stream_V, AESL_token); // [[/transaction]]
		}

		// pop stream input: "in_stream"
		aesl_fh.read(WRAPC_STREAM_SIZE_IN_in_stream_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_IN_in_stream_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_IN_in_stream_V, AESL_token); // pop_size
			int aesl_tmp_4 = atoi(AESL_token.c_str());
			for (int i = 0; i < aesl_tmp_4; i++)
			{
				in_stream.read();
			}
			aesl_fh.read(WRAPC_STREAM_SIZE_IN_in_stream_V, AESL_token); // [[/transaction]]
		}

		// output port post check: "out_stream_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_out_stream_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_out_stream_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_out_stream_V, AESL_token); // data

			std::vector<sc_bv<32> > out_stream_V_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_stream_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_stream_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					out_stream_V_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_out_stream_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_out_stream_V))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_1)
			{
				aesl_tmp_1 = i;
			}

			if (aesl_tmp_1 > 0 && aesl_tmp_0.size() < aesl_tmp_1)
			{
				int aesl_tmp_0_size = aesl_tmp_0.size();

				for (int tmp_aesl_tmp_0 = 0; tmp_aesl_tmp_0 < aesl_tmp_1 - aesl_tmp_0_size; tmp_aesl_tmp_0++)
				{
					int tmp;
					aesl_tmp_0.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: out_stream_V
				{
					// bitslice(31, 0)
					// {
						// celement: out_stream.V(31, 0)
						// {
							sc_lv<32>* out_stream_V_lv0_0_0_1 = new sc_lv<32>[aesl_tmp_1 - aesl_tmp_2];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: out_stream.V(31, 0)
						{
							// carray: (aesl_tmp_2) => (aesl_tmp_1 - 1) @ (1)
							for (int i_0 = aesl_tmp_2; i_0 <= aesl_tmp_1 - 1; i_0 += 1)
							{
								if (&(aesl_tmp_0[0]) != NULL) // check the null address if the c port is array or others
								{
									out_stream_V_lv0_0_0_1[hls_map_index].range(31, 0) = sc_bv<32>(out_stream_V_pc_buffer[hls_map_index].range(31, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: out_stream.V(31, 0)
						{
							// carray: (aesl_tmp_2) => (aesl_tmp_1 - 1) @ (1)
							for (int i_0 = aesl_tmp_2; i_0 <= aesl_tmp_1 - 1; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : aesl_tmp_0[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : aesl_tmp_0[0]
								// output_left_conversion : aesl_tmp_0[i_0]
								// output_type_conversion : (out_stream_V_lv0_0_0_1[hls_map_index]).to_uint64()
								if (&(aesl_tmp_0[0]) != NULL) // check the null address if the c port is array or others
								{
									aesl_tmp_0[i_0] = (out_stream_V_lv0_0_0_1[hls_map_index]).to_uint64();
									hls_map_index++;
								}
							}
						}
					}
				}
			}
		}

		// push back output stream: "out_stream"
		for (int i = 0; i < aesl_tmp_1; i++)
		{
			out_stream.write(aesl_tmp_0[i]);
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "out_stream_V"
		char* tvin_out_stream_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_out_stream_V);
		char* tvout_out_stream_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_out_stream_V);
		char* wrapc_stream_size_out_out_stream_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_out_stream_V);
		char* wrapc_stream_egress_status_out_stream_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_out_stream_V);

		// "in_stream_V"
		char* tvin_in_stream_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_in_stream_V);
		char* wrapc_stream_size_in_in_stream_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_IN_in_stream_V);
		char* wrapc_stream_ingress_status_in_stream_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_INGRESS_STATUS_in_stream_V);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// dump stream tvin: "out_stream"
		std::vector<int > aesl_tmp_0;
		int aesl_tmp_1 = 0;
		while (!out_stream.empty())
		{
			aesl_tmp_0.push_back(out_stream.read());
			aesl_tmp_1++;
		}

		// dump stream tvin: "in_stream"
		std::vector<int > aesl_tmp_3;
		int aesl_tmp_4 = 0;
		while (!in_stream.empty())
		{
			aesl_tmp_3.push_back(in_stream.read());
			aesl_tmp_4++;
		}

		// push back input stream: "out_stream"
		for (int i = 0; i < aesl_tmp_1; i++)
		{
			out_stream.write(aesl_tmp_0[i]);
		}

		// push back input stream: "in_stream"
		for (int i = 0; i < aesl_tmp_4; i++)
		{
			in_stream.write(aesl_tmp_3[i]);
		}

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		do_convolution(out_stream, in_stream);

		CodeState = DUMP_OUTPUTS;
		// pop output stream: "out_stream"
		int aesl_tmp_2 = aesl_tmp_1;
		aesl_tmp_1 = 0;
     aesl_tmp_0.clear();
		while (!out_stream.empty())
		{
			aesl_tmp_0.push_back(out_stream.read());
			aesl_tmp_1++;
		}

		// record input size to tv3: "in_stream"
		int aesl_tmp_5 = in_stream.size();

		// [[transaction]]
		sprintf(tvout_out_stream_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_out_stream_V, tvout_out_stream_V);

		sc_bv<32>* out_stream_V_tvout_wrapc_buffer = new sc_bv<32>[aesl_tmp_1 - aesl_tmp_2];

		// RTL Name: out_stream_V
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: out_stream.V(31, 0)
				{
					// carray: (aesl_tmp_2) => (aesl_tmp_1 - 1) @ (1)
					for (int i_0 = aesl_tmp_2; i_0 <= aesl_tmp_1 - 1; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : aesl_tmp_0[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : aesl_tmp_0[0]
						// regulate_c_name       : out_stream_V
						// input_type_conversion : aesl_tmp_0[i_0]
						if (&(aesl_tmp_0[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> out_stream_V_tmp_mem;
							out_stream_V_tmp_mem = aesl_tmp_0[i_0];
							out_stream_V_tvout_wrapc_buffer[hls_map_index].range(31, 0) = out_stream_V_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2; i++)
		{
			sprintf(tvout_out_stream_V, "%s\n", (out_stream_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_out_stream_V, tvout_out_stream_V);
		}

		tcl_file.set_num(aesl_tmp_1 - aesl_tmp_2, &tcl_file.out_stream_V_depth);
		sprintf(tvout_out_stream_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_out_stream_V, tvout_out_stream_V);

		// release memory allocation
		delete [] out_stream_V_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_out_stream_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_stream_V, wrapc_stream_size_out_out_stream_V);
		sprintf(wrapc_stream_size_out_out_stream_V, "%d\n", aesl_tmp_1 - aesl_tmp_2);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_stream_V, wrapc_stream_size_out_out_stream_V);
		sprintf(wrapc_stream_size_out_out_stream_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_stream_V, wrapc_stream_size_out_out_stream_V);

		// [[transaction]]
		sprintf(tvin_in_stream_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_in_stream_V, tvin_in_stream_V);
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_in_stream_V, tvin_in_stream_V);

		sc_bv<32>* in_stream_V_tvin_wrapc_buffer = new sc_bv<32>[aesl_tmp_4 - aesl_tmp_5];

		// RTL Name: in_stream_V
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: in_stream.V(31, 0)
				{
					// carray: (0) => (aesl_tmp_4 - aesl_tmp_5 - 1) @ (1)
					for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : aesl_tmp_3[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : aesl_tmp_3[0]
						// regulate_c_name       : in_stream_V
						// input_type_conversion : aesl_tmp_3[i_0]
						if (&(aesl_tmp_3[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> in_stream_V_tmp_mem;
							in_stream_V_tmp_mem = aesl_tmp_3[i_0];
							in_stream_V_tvin_wrapc_buffer[hls_map_index].range(31, 0) = in_stream_V_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_4 - aesl_tmp_5; i++)
		{
			sprintf(tvin_in_stream_V, "%s\n", (in_stream_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_in_stream_V, tvin_in_stream_V);
		}

		// dump stream ingress status to file
		sc_int<32> stream_ingress_size_in_stream_V = aesl_tmp_4;
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_in_stream_V, stream_ingress_size_in_stream_V.to_string().c_str());
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_in_stream_V, "\n");

		for (int i = 0; i < aesl_tmp_4 - aesl_tmp_5; i++)
		{
			stream_ingress_size_in_stream_V--;
			aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_in_stream_V, stream_ingress_size_in_stream_V.to_string().c_str());
			aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_in_stream_V, "\n");
		}

		tcl_file.set_num(aesl_tmp_4 - aesl_tmp_5, &tcl_file.in_stream_V_depth);
		sprintf(tvin_in_stream_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_in_stream_V, tvin_in_stream_V);
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_in_stream_V, tvin_in_stream_V);

		// release memory allocation
		delete [] in_stream_V_tvin_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_in_in_stream_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_in_stream_V, wrapc_stream_size_in_in_stream_V);
		sprintf(wrapc_stream_size_in_in_stream_V, "%d\n", aesl_tmp_4 - aesl_tmp_5);
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_in_stream_V, wrapc_stream_size_in_in_stream_V);
		sprintf(wrapc_stream_size_in_in_stream_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_in_stream_V, wrapc_stream_size_in_in_stream_V);

		// push back output stream: "out_stream"
		for (int i = 0; i < aesl_tmp_1; i++)
		{
			out_stream.write(aesl_tmp_0[i]);
		}

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "out_stream_V"
		delete [] tvout_out_stream_V;
		delete [] tvin_out_stream_V;
		delete [] wrapc_stream_size_out_out_stream_V;
		// release memory allocation: "in_stream_V"
		delete [] tvin_in_stream_V;
		delete [] wrapc_stream_size_in_in_stream_V;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

